version: '2'

services:
  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'

  account-tool:
    build: .
    depends_on:
      - maildev
    volumes:
      - './src:/app/src'
    ports:
      - '8080:8080'
      - '8081:8081'
      - '5005:5005'
    environment:
      SPRING_PROFILES_ACTIVE: development,maildev
