#!/bin/sh

# make the start script executable
chmod +x /usr/share/account-tool/bin/account-tool

# Create a config directory and empty override.yaml file
# If the file is empty or doesn't exists the application will start the
# build-in profile. Own Profiles or Configurations can be stored there,
# they have to be configured over SPRING_CONFIG_LOCATION environment variable
# or edited in /etc/default/accounttool file
CONF_DIR="/usr/share/account-tool/conf"
if [ -d ${CONF_DIR} ]; then
	echo "Configuration directory ${CONF_DIR} already exists."
else
	mkdir ${CONF_DIR}
	chown accounttool:accounttool ${CONF_DIR}
	echo "Created config directory ${CONF_DIR} for configuration overrides."
fi

# Create the empty overrides.yaml file.
OVERRIDE_CONFIG="${CONF_DIR}/overrides.yaml"
if [ -f ${OVERRIDE_CONFIG} ]; then
	echo "File ${OVERRIDE_CONFIG} exists."
else
	touch ${OVERRIDE_CONFIG}
	chown accounttool:accounttool ${OVERRIDE_CONFIG}
	echo "Created empty override configuration file ${OVERRIDE_CONFIG}."
fi


# register and enabled the systemd unit
systemctl enable accounttool

# start new service
systemctl start accounttool
