#!/bin/sh

USER_AND_GROUP=accounttool

# Create system group
if grep -q ${USER_AND_GROUP} /etc/group ; then
	echo "Group ${USER_AND_GROUP} already exists"
else
	addgroup --system ${USER_AND_GROUP}
fi

# Create system user
id -u ${USER_AND_GROUP} || adduser --system --no-create-home --ingroup ${USER_AND_GROUP} ${USER_AND_GROUP}
